version: "3.8"

services:
  mongodb:
    image: mongo:7.0.21-jammy
    container_name: my-mongo
    ports:
      - "27007:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      TZ: UTC
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
