


services:
  # FastAPI Application
  fastapi:
    build:
      context: ..
      dockerfile: docker/minirag/Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    volumes:
      - fastapi_data:/app/assets
    networks:
      - backend
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - ./env/.env.app

  # Nginx Service
  nginx:
    image: nginx:stable-alpine3.20-perl
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
      - backend
    restart: always


 

  # Qdrant (VectorDB)
  qdrant:
    image: qdrant/qdrant:v1.13.6
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend
    restart: always

  # Prometheus Monitoring
  prometheus:
    image: prom/prometheus:v3.3.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - backend
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:11.6.0-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./env/.env.grafana
    depends_on:
      - prometheus
    networks:
      - backend
    restart: always


  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - backend
    restart: always


# MongoDB Service
  mongodb:
    image: mongo:7.0.21-jammy
    container_name: my-mongodb
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db
    env_file:
      - ./env/.env.mongodb
    networks:
      - backend
    restart: always
    healthcheck:
      test: |
        mongosh --eval "
        db.adminCommand('ping').ok === 1 ? 
        quit(0) : 
        quit(1)
        " --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  # MongoDB Exporter for MongoDB metrics
  mongodb-exporter:
    image: percona/mongodb_exporter:0.40.0
    container_name: mongodb-exporter
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URI=mongodb://root1:example1@mongodb:27017/admin?authSource=admin
    # Adjust command if necessary. Often just the URI is enough, but you can add flags:
    command:
      - '--collect-all' # Ensures all collectors are enabled
    depends_on:
      - mongodb
    networks:
      - backend
    restart: always




networks:
  backend:
    driver: bridge

volumes:
  fastapi_data:
  qdrant_data:
  prometheus_data:
  grafana_data:
  mongodb_data:
